#include "OpenSHC/Map/Buildings/BuildingsState.func.hpp"
#include "OpenSHC/Commands/MappersEnum.hpp"
#include "OpenSHC/Map/Buildings/BuildingType.hpp"

namespace OpenSHC {
namespace Map {
    namespace Buildings {

        using OpenSHC::Commands::MappersEnum;
        using OpenSHC::Map::Buildings::BuildingType;

        // FUNCTION: STRONGHOLDCRUSADER 0x00409370
        BuildingType BuildingsState::convertCommandBuildingTypeToBuildingType(MappersEnum commandBuildingType)
        {
            switch (commandBuildingType) {
            case OpenSHC::Commands::M_MAPPER_FLETCHER:
                return BT_FLETCHER;
            case OpenSHC::Commands::M_MAPPER_POLETURNER:
                return BT_POLETURNER;
            case OpenSHC::Commands::M_MAPPER_BLACKSMITH:
                return BT_BLACKSMITH;
            case OpenSHC::Commands::M_MAPPER_ARMOURER:
                return BT_ARMOURER;
            case OpenSHC::Commands::M_MAPPER_TANNER:
                return BT_TANNER;
            case OpenSHC::Commands::M_MAPPER_WOODSMAN:
                return BT_WOODCUTTERSHUT;
            case OpenSHC::Commands::M_MAPPER_OXENBASE:
                return BT_OXTETHER;
            case OpenSHC::Commands::M_MAPPER_QUARRY:
                return BT_QUARRY;
            case OpenSHC::Commands::M_MAPPER_QUARRYPILE:
                return BT_QUARRYSTOCKPILE;
            case OpenSHC::Commands::M_MAPPER_STORES:
                return BT_STOCKPILE;
            case OpenSHC::Commands::M_MAPPER_GRANARY:
                return BT_GRANARY;
            case OpenSHC::Commands::M_MAPPER_ARMOURY:
                return BT_ARMORY;
            case OpenSHC::Commands::M_MAPPER_STABLES:
                return BT_STABLES;
            case OpenSHC::Commands::M_MAPPER_OIL_SMELTER:
                return BT_OILSMELTER;
            case OpenSHC::Commands::M_MAPPER_BARRACKS_EURO:
                return BT_MERCENARYPOST;
            case OpenSHC::Commands::M_MAPPER_BARRACKS_ARAB:
                return BT_BARRACKS;
            case OpenSHC::Commands::M_MAPPER_OUTPOST_EURO:
                return BT_OUTPOST_EUROPEAN;
            case OpenSHC::Commands::M_MAPPER_OUTPOST_ARAB:
                return BT_OUTPOST_ARABIAN;
            case OpenSHC::Commands::M_MAPPER_OUTPOST_BEDOUIN:
                return BT_HOUSE;
            case OpenSHC::Commands::M_MAPPER_HOVEL:
                return BT_HOVEL;
            case OpenSHC::Commands::M_MAPPER_WHEATFARM:
                return BT_WHEATFARM;
            case OpenSHC::Commands::M_MAPPER_HOPSFARM:
                return BT_HOPFARM;
            case OpenSHC::Commands::M_MAPPER_APPLEFARM:
                return BT_APPLEFARM;
            case OpenSHC::Commands::M_MAPPER_CATTLEFARM:
                return BT_DAIRYFARM;
            case OpenSHC::Commands::M_MAPPER_MILL:
                return BT_MILL;
            case OpenSHC::Commands::M_MAPPER_TRADEPOST:
                return BT_MARKETPLACE;
            case OpenSHC::Commands::M_MAPPER_HUNTER:
                return BT_HUNTERSHUT;
            case OpenSHC::Commands::M_MAPPER_BAKER:
                return BT_BAKERY;
            case OpenSHC::Commands::M_MAPPER_BREWER:
                return BT_BREWERY;
            case OpenSHC::Commands::M_MAPPER_INN:
                return BT_INN;
            case OpenSHC::Commands::M_MAPPER_HEALER:
                return BT_APOTHECARY;
            case OpenSHC::Commands::M_MAPPER_IRON_MINE:
                return BT_IRONMINE;
            case OpenSHC::Commands::M_MAPPER_PITCH_WORKINGS:
                return BT_PITCHRIG;
            case OpenSHC::Commands::M_MAPPER_TOWER:
                return BT_TOWER;
            case OpenSHC::Commands::M_MAPPER_GATE_MAIN:
            case OpenSHC::Commands::M_MAPPER_GATE_STONE2A:
            case OpenSHC::Commands::M_MAPPER_GATE_STONE2B:
                return BT_GATEHOUSELARGE;
            case OpenSHC::Commands::M_MAPPER_GATE_INNER:
            case OpenSHC::Commands::M_MAPPER_GATE_STONE1A:
            case OpenSHC::Commands::M_MAPPER_GATE_STONE1B:
                return BT_GATEHOUSESMALL;
            case OpenSHC::Commands::M_MAPPER_GATE_WOOD1A:
            case OpenSHC::Commands::M_MAPPER_GATE_WOOD1B:
            case OpenSHC::Commands::M_MAPPER_GATE_WOOD1C:
            case OpenSHC::Commands::M_MAPPER_GATE_WOOD1D:
                return BT_WOODGATE1;
            case OpenSHC::Commands::M_MAPPER_GATE_POSTERN:
                return BT_WOODGATE2;
            case OpenSHC::Commands::M_MAPPER_DRAWBRIDGE:
                return BT_DRAWBRIDGE;
            case OpenSHC::Commands::M_MAPPER_CHURCH1:
                return BT_CHAPEL;
            case OpenSHC::Commands::M_MAPPER_CHURCH2:
                return BT_CHURCH;
            case OpenSHC::Commands::M_MAPPER_CHURCH3:
                return BT_CATHEDRAL;
            case OpenSHC::Commands::M_MAPPER_ENGINEERS_GUILD:
                return BT_ENGINEERSGUILD;
            case OpenSHC::Commands::M_MAPPER_TUNNELERS_GUILD:
                return BT_TUNNELERSGUILD;
            case OpenSHC::Commands::M_MAPPER_TUNNEL_CONSTRUCTION:
                return BT_UNKNOWN4;
            case OpenSHC::Commands::M_MAPPER_TUNNEL:
                return BT_TUNNEL;
            case OpenSHC::Commands::M_MAPPER_SIGNPOST:
                return BT_SIGNPOST;
            case OpenSHC::Commands::M_MAPPER_KEEP1:
                return BT_MANORHOUSE;
            case OpenSHC::Commands::M_MAPPER_KEEP2:
                return BT_STONEKEEP;
            case OpenSHC::Commands::M_MAPPER_KEEP3:
                return BT_STRONGHOLD;
            case OpenSHC::Commands::M_MAPPER_TOWER1:
                return BT_TOWER1;
            case OpenSHC::Commands::M_MAPPER_TOWER2:
                return BT_TOWER2;
            case OpenSHC::Commands::M_MAPPER_TOWER3:
                return BT_TOWER3;
            case OpenSHC::Commands::M_MAPPER_TOWER4:
                return BT_TOWER4;
            case OpenSHC::Commands::M_MAPPER_TOWER5:
                return BT_TOWER5;
            case OpenSHC::Commands::M_MAPPER_TOWER1_DESTROYED:
            case OpenSHC::Commands::M_MAPPER_MANGONEL:
                return BT_MANGONEL;
            case OpenSHC::Commands::M_MAPPER_TOWER2_DESTROYED:
            case OpenSHC::Commands::M_MAPPER_BALLISTA:
                return BT_BALLISTA;
            case OpenSHC::Commands::M_MAPPER_TOWER3_DESTROYED:
                return BT_UNKNOWN5;
            case OpenSHC::Commands::M_MAPPER_TOWER4_DESTROYED:
                return BT_UNKNOWN6;
            case OpenSHC::Commands::M_MAPPER_TOWER5_DESTROYED:
                return BT_UNKNOWN3;
            case OpenSHC::Commands::M_MAPPER_GARDEN1:
            case OpenSHC::Commands::M_MAPPER_GARDEN2:
            case OpenSHC::Commands::M_MAPPER_GARDEN3:
            case OpenSHC::Commands::M_MAPPER_GARDEN4:
            case OpenSHC::Commands::M_MAPPER_GARDEN5:
            case OpenSHC::Commands::M_MAPPER_GARDEN6:
            case OpenSHC::Commands::M_MAPPER_GARDEN7:
            case OpenSHC::Commands::M_MAPPER_GARDEN8:
            case OpenSHC::Commands::M_MAPPER_GARDEN9:
            case OpenSHC::Commands::M_MAPPER_GARDEN10:
            case OpenSHC::Commands::M_MAPPER_GARDEN11:
            case OpenSHC::Commands::M_MAPPER_GARDEN12:
                return BT_GARDEN;
            case (MappersEnum)248:
            case (MappersEnum)249:
            case (MappersEnum)250:
            case (MappersEnum)251:
            case (MappersEnum)252:
            case (MappersEnum)253:
            case (MappersEnum)254:
            case (MappersEnum)255:
            case (MappersEnum)256:
            case (MappersEnum)257:
            case (MappersEnum)258:
            case (MappersEnum)259:
            case (MappersEnum)260:
                return BT_UNKNOWN1;
            case OpenSHC::Commands::M_MAPPER_MAYPOLE:
                return BT_MAYPOLE;
            case OpenSHC::Commands::M_MAPPER_GALLOWS:
                return BT_GALLOWS;
            case OpenSHC::Commands::M_MAPPER_STOCKS:
                return BT_STOCKS;
            case OpenSHC::Commands::M_MAPPER_CATAPULT:
                return BT_CATAPULT;
            case OpenSHC::Commands::M_MAPPER_PEOPLE_ARAB_BALLISTA:
            case OpenSHC::Commands::M_MAPPER_ARAB_BALLISTA:
                return BT_FIREBALLISTA;
            case OpenSHC::Commands::M_MAPPER_TREBUCHET:
                return BT_TREBUCHET;
            case OpenSHC::Commands::M_MAPPER_SIEGE_TOWER:
                return BT_BATTERINGRAM;
            case OpenSHC::Commands::M_MAPPER_BATTERING_RAM:
                return BT_SIEGETOWER;
            case OpenSHC::Commands::M_MAPPER_PORTABLE_SHIELD:
                return BT_SHIELD;
            case OpenSHC::Commands::M_MAPPER_KILLING_PIT:
                return BT_KILLINGPIT;
            case OpenSHC::Commands::M_MAPPER_PITCH_DITCH:
                return BT_PITCHDITCH;
            case OpenSHC::Commands::M_MAPPER_SIEGE_TOWER_BASE:
                return BT_SIEGETOWER_PLACED;
            case OpenSHC::Commands::M_MAPPER_CESS_PIT1:
            case OpenSHC::Commands::M_MAPPER_CESS_PIT2:
            case OpenSHC::Commands::M_MAPPER_CESS_PIT3:
            case OpenSHC::Commands::M_MAPPER_CESS_PIT4:
                return BT_CESSPIT;
            case OpenSHC::Commands::M_MAPPER_BURNING_STAKE:
                return BT_BURNINGSTAKE;
            case OpenSHC::Commands::M_MAPPER_GIBBET:
                return BT_GIBBET;
            case OpenSHC::Commands::M_MAPPER_DUNGEON:
                return BT_DUNGEON;
            case OpenSHC::Commands::M_MAPPER_RACK_STRETCHING:
                return BT_STRETCHINGRACK;
            case OpenSHC::Commands::M_MAPPER_RACK_FLOGGING:
                return BT_RACKFLOGGING;
            case OpenSHC::Commands::M_MAPPER_CHOPPING_BLOCK:
                return BT_CHOPPINGBLOCK;
            case OpenSHC::Commands::M_MAPPER_DUNKING_STOOL:
                return BT_DUNKINGSTOOL;
            case OpenSHC::Commands::M_MAPPER_DOG_CAGE:
                return BT_DOGCAGE;
            case OpenSHC::Commands::M_MAPPER_STATUE1:
            case OpenSHC::Commands::M_MAPPER_STATUE2:
            case OpenSHC::Commands::M_MAPPER_STATUE3:
            case OpenSHC::Commands::M_MAPPER_STATUE4:
            case OpenSHC::Commands::M_MAPPER_STATUE5:
                return BT_STATUE;
            case OpenSHC::Commands::M_MAPPER_SHRINE1:
            case OpenSHC::Commands::M_MAPPER_SHRINE2:
            case OpenSHC::Commands::M_MAPPER_SHRINE3:
            case OpenSHC::Commands::M_MAPPER_SHRINE4:
            case OpenSHC::Commands::M_MAPPER_SHRINE5:
                return BT_SHRINE;
            case OpenSHC::Commands::M_MAPPER_BEE_HIVE:
                return BT_BEEHIVE;
            case OpenSHC::Commands::M_MAPPER_DANCING_BEAR:
                return BT_DANCINGBEAR;
            case OpenSHC::Commands::M_MAPPER_POND1:
            case OpenSHC::Commands::M_MAPPER_POND2_SMALL:
            case OpenSHC::Commands::M_MAPPER_POND3_LARGE1:
            case OpenSHC::Commands::M_MAPPER_POND4_LARGE2:
                return BT_POND;
            case OpenSHC::Commands::M_MAPPER_BEAR_CAVE:
                return BT_BEARCAVE;
            case OpenSHC::Commands::M_MAPPER_WELL:
                return BT_WELL;
            case OpenSHC::Commands::M_MAPPER_WATERPOT:
                return BT_WATERPOT;
            default:
                return (BuildingType)0;
            }
        }

    }
}
}
