#include "OpenSHC/Map/Buildings/BuildingsState.func.hpp"
#include "OpenSHC/Commands/MappersEnum.hpp"

namespace OpenSHC {
namespace Map {
    namespace Buildings {

        using OpenSHC::Commands::MappersEnum;

        // FUNCTION: STRONGHOLDCRUSADER 0x00409930
        MappersEnum BuildingsState::convertBuildingTypeToCommandBuildingType(BuildingType buildingType)
        {
            switch (buildingType) {
            case BT_FLETCHER:
                return OpenSHC::Commands::M_MAPPER_FLETCHER;
            case BT_POLETURNER:
                return OpenSHC::Commands::M_MAPPER_POLETURNER;
            case BT_BLACKSMITH:
                return OpenSHC::Commands::M_MAPPER_BLACKSMITH;
            case BT_ARMOURER:
                return OpenSHC::Commands::M_MAPPER_ARMOURER;
            case BT_TANNER:
                return OpenSHC::Commands::M_MAPPER_TANNER;
            case BT_WOODCUTTERSHUT:
                return OpenSHC::Commands::M_MAPPER_WOODSMAN;
            case BT_OXTETHER:
                return OpenSHC::Commands::M_MAPPER_OXENBASE;
            case BT_QUARRY:
                return OpenSHC::Commands::M_MAPPER_QUARRY;
            case BT_STOCKPILE:
                return OpenSHC::Commands::M_MAPPER_STORES;
            case BT_GRANARY:
                return OpenSHC::Commands::M_MAPPER_GRANARY;
            case BT_ARMORY:
                return OpenSHC::Commands::M_MAPPER_ARMOURY;
            case BT_STABLES:
                return OpenSHC::Commands::M_MAPPER_STABLES;
            case BT_OILSMELTER:
                return OpenSHC::Commands::M_MAPPER_OIL_SMELTER;
            case BT_MERCENARYPOST:
                return OpenSHC::Commands::M_MAPPER_BARRACKS_EURO;
            case BT_BARRACKS:
                return OpenSHC::Commands::M_MAPPER_BARRACKS_ARAB;
            case BT_OUTPOST_EUROPEAN:
                return OpenSHC::Commands::M_MAPPER_OUTPOST_EURO;
            case BT_OUTPOST_ARABIAN:
                return OpenSHC::Commands::M_MAPPER_OUTPOST_ARAB;
            case BT_HOUSE:
                return OpenSHC::Commands::M_MAPPER_OUTPOST_BEDOUIN;
            case BT_HOVEL:
                return OpenSHC::Commands::M_MAPPER_HOVEL;
            case BT_WHEATFARM:
                return OpenSHC::Commands::M_MAPPER_WHEATFARM;
            case BT_HOPFARM:
                return OpenSHC::Commands::M_MAPPER_HOPSFARM;
            case BT_APPLEFARM:
                return OpenSHC::Commands::M_MAPPER_APPLEFARM;
            case BT_DAIRYFARM:
                return OpenSHC::Commands::M_MAPPER_CATTLEFARM;
            case BT_MILL:
                return OpenSHC::Commands::M_MAPPER_MILL;
            case BT_MARKETPLACE:
                return OpenSHC::Commands::M_MAPPER_TRADEPOST;
            case BT_HUNTERSHUT:
                return OpenSHC::Commands::M_MAPPER_HUNTER;
            case BT_BAKERY:
                return OpenSHC::Commands::M_MAPPER_BAKER;
            case BT_BREWERY:
                return OpenSHC::Commands::M_MAPPER_BREWER;
            case BT_INN:
                return OpenSHC::Commands::M_MAPPER_INN;
            case BT_APOTHECARY:
                return OpenSHC::Commands::M_MAPPER_HEALER;
            case BT_IRONMINE:
                return OpenSHC::Commands::M_MAPPER_IRON_MINE;
            case BT_PITCHRIG:
                return OpenSHC::Commands::M_MAPPER_PITCH_WORKINGS;
            case BT_TOWER:
                return OpenSHC::Commands::M_MAPPER_TOWER;
            case BT_GATEHOUSELARGE:
                return OpenSHC::Commands::M_MAPPER_GATE_MAIN;
            case BT_GATEHOUSESMALL:
                return OpenSHC::Commands::M_MAPPER_GATE_INNER;
            case BT_DRAWBRIDGE:
                return OpenSHC::Commands::M_MAPPER_DRAWBRIDGE;
            case BT_CHAPEL:
                return OpenSHC::Commands::M_MAPPER_CHURCH1;
            case BT_CHURCH:
                return OpenSHC::Commands::M_MAPPER_CHURCH2;
            case BT_CATHEDRAL:
                return OpenSHC::Commands::M_MAPPER_CHURCH3;
            case BT_ENGINEERSGUILD:
                return OpenSHC::Commands::M_MAPPER_ENGINEERS_GUILD;
            case BT_TUNNELERSGUILD:
                return OpenSHC::Commands::M_MAPPER_TUNNELERS_GUILD;
            case BT_UNKNOWN4:
                return OpenSHC::Commands::M_MAPPER_TUNNEL_CONSTRUCTION;
            case BT_TUNNEL:
                return OpenSHC::Commands::M_MAPPER_TUNNEL;
            case BT_SIGNPOST:
                return OpenSHC::Commands::M_MAPPER_SIGNPOST;
            case BT_MANORHOUSE:
                return OpenSHC::Commands::M_MAPPER_KEEP1;
            case BT_STONEKEEP:
                return OpenSHC::Commands::M_MAPPER_KEEP2;
            case BT_STRONGHOLD:
                return OpenSHC::Commands::M_MAPPER_KEEP3;
            case BT_TOWER1:
                return OpenSHC::Commands::M_MAPPER_TOWER1;
            case BT_TOWER2:
                return OpenSHC::Commands::M_MAPPER_TOWER2;
            case BT_TOWER3:
                return OpenSHC::Commands::M_MAPPER_TOWER3;
            case BT_TOWER4:
                return OpenSHC::Commands::M_MAPPER_TOWER4;
            case BT_TOWER5:
                return OpenSHC::Commands::M_MAPPER_TOWER5;
            case BT_MANGONEL:
                return OpenSHC::Commands::M_MAPPER_TOWER1_DESTROYED;
            case BT_BALLISTA:
                return OpenSHC::Commands::M_MAPPER_TOWER2_DESTROYED;
            case BT_UNKNOWN5:
                return OpenSHC::Commands::M_MAPPER_TOWER3_DESTROYED;
            case BT_UNKNOWN6:
                return OpenSHC::Commands::M_MAPPER_TOWER4_DESTROYED;
            case BT_UNKNOWN3:
                return OpenSHC::Commands::M_MAPPER_TOWER5_DESTROYED;
            case BT_GARDEN:
                return OpenSHC::Commands::M_MAPPER_GARDEN1;
            case BT_UNKNOWN1:
                return (MappersEnum)248;
            case BT_MAYPOLE:
                return OpenSHC::Commands::M_MAPPER_MAYPOLE;
            case BT_GALLOWS:
                return OpenSHC::Commands::M_MAPPER_GALLOWS;
            case BT_STOCKS:
                return OpenSHC::Commands::M_MAPPER_STOCKS;
            case BT_CATAPULT:
                return OpenSHC::Commands::M_MAPPER_CATAPULT;
            case BT_FIREBALLISTA:
                return OpenSHC::Commands::M_MAPPER_ARAB_BALLISTA;
            case BT_TREBUCHET:
                return OpenSHC::Commands::M_MAPPER_TREBUCHET;
            case BT_BATTERINGRAM:
                return OpenSHC::Commands::M_MAPPER_SIEGE_TOWER;
            case BT_SIEGETOWER:
                return OpenSHC::Commands::M_MAPPER_BATTERING_RAM;
            case BT_SHIELD:
                return OpenSHC::Commands::M_MAPPER_PORTABLE_SHIELD;
            case BT_KILLINGPIT:
                return OpenSHC::Commands::M_MAPPER_KILLING_PIT;
            case BT_PITCHDITCH:
                return OpenSHC::Commands::M_MAPPER_PITCH_DITCH;
            case BT_SIEGETOWER_PLACED:
                return OpenSHC::Commands::M_MAPPER_SIEGE_TOWER_BASE;
            case BT_CESSPIT:
                return OpenSHC::Commands::M_MAPPER_CESS_PIT4;
            case BT_BURNINGSTAKE:
                return OpenSHC::Commands::M_MAPPER_BURNING_STAKE;
            case BT_GIBBET:
                return OpenSHC::Commands::M_MAPPER_GIBBET;
            case BT_DUNGEON:
                return OpenSHC::Commands::M_MAPPER_DUNGEON;
            case BT_STRETCHINGRACK:
                return OpenSHC::Commands::M_MAPPER_RACK_STRETCHING;
            case BT_RACKFLOGGING:
                return OpenSHC::Commands::M_MAPPER_RACK_FLOGGING;
            case BT_CHOPPINGBLOCK:
                return OpenSHC::Commands::M_MAPPER_CHOPPING_BLOCK;
            case BT_DUNKINGSTOOL:
                return OpenSHC::Commands::M_MAPPER_DUNKING_STOOL;
            case BT_DOGCAGE:
                return OpenSHC::Commands::M_MAPPER_DOG_CAGE;
            case BT_STATUE:
                return OpenSHC::Commands::M_MAPPER_STATUE5;
            case BT_SHRINE:
                return OpenSHC::Commands::M_MAPPER_SHRINE5;
            case BT_DANCINGBEAR:
                return OpenSHC::Commands::M_MAPPER_DANCING_BEAR;
            case BT_POND:
                return OpenSHC::Commands::M_MAPPER_POND4_LARGE2;
            case BT_BEARCAVE:
                return OpenSHC::Commands::M_MAPPER_BEAR_CAVE;
            case BT_WELL:
                return OpenSHC::Commands::M_MAPPER_WELL;
            case BT_WATERPOT:
                return OpenSHC::Commands::M_MAPPER_WATERPOT;
            default:
                return OpenSHC::Commands::M_MAPPER_NULL;
            }
        }

    }
}
}
