#include "../AICState.func.hpp"

#include "OpenSHC/AI/AIC/AITargetChoice.hpp"

namespace OpenSHC {
namespace AI {

    using OpenSHC::AI::AIC::AITargetChoice;

    // FUNCTION: STRONGHOLDCRUSADER 0x004C9900
    void AICState::setAICParameters_12(int aicIndex)
    {
        this->aics[aicIndex].flagType = 10;
        this->aics[aicIndex].unknown001 = 0;
        this->aics[aicIndex].unknown002 = 0;
        this->aics[aicIndex].unknown003 = 0;
        this->aics[aicIndex].unknown004 = 1;
        this->aics[aicIndex].unknown005 = 1;
        this->aics[aicIndex].criticalPopularity = 0x1194;
        this->aics[aicIndex].lowestPopularity = 5000;
        this->aics[aicIndex].highestPopularity = 9000;
        this->aics[aicIndex].taxesMin = 2;
        this->aics[aicIndex].taxesMax = 0xc;
        this->aics[aicIndex].unknown011 = 10;
        this->aics[aicIndex].farm1 = 0x1e;
        this->aics[aicIndex].farm2 = 0x20;
        this->aics[aicIndex].farm3 = 0x1e;
        this->aics[aicIndex].farm4 = 0x1f;
        this->aics[aicIndex].populationPerFarm = 4;
        this->aics[aicIndex].populationPerWoodcutter = 7;
        this->aics[aicIndex].populationPerQuarry = 6;
        this->aics[aicIndex].populationPerIronmine = 10;
        this->aics[aicIndex].populationPerPitchrig = 0;
        this->aics[aicIndex].maxQuarries = 4;
        this->aics[aicIndex].maxIronmines = 3;
        this->aics[aicIndex].maxWoodcutters = 10;
        this->aics[aicIndex].maxPitchrigs = 1;
        this->aics[aicIndex].maxFarms = 0x10;
        this->aics[aicIndex].buildInterval = 2;
        this->aics[aicIndex].resourceRebuildDelay = 0x28;
        this->aics[aicIndex].maxFood = 0x50;
        this->aics[aicIndex].minimumApples = 10;
        this->aics[aicIndex].minimumCheese = -1;
        this->aics[aicIndex].minimumBread = -1;
        this->aics[aicIndex].minimumWheat = 2;
        this->aics[aicIndex].minimumHop = 2;
        this->aics[aicIndex].tradeAmountFood = 0x14;
        this->aics[aicIndex].tradeAmountEquipment = 0;
        this->aics[aicIndex].aiRequestDelay = 0xc;
        this->aics[aicIndex].minimumGoodsRequiredAfterTrade = 10;
        this->aics[aicIndex].doubleRationsFoodThreshold = 0x28;
        this->aics[aicIndex].maxWood = 0x3c;
        this->aics[aicIndex].maxStone = 0x3c;
        this->aics[aicIndex].maxResourceOther = 10;
        this->aics[aicIndex].maxEquipment = 4;
        this->aics[aicIndex].maxBeer = 10;
        this->aics[aicIndex].maxResourceVariance = 4;
        this->aics[aicIndex].recruitGoldThreshold = 200;
        this->aics[aicIndex].blacksmithSetting = 0x16;
        this->aics[aicIndex].fletcherSetting = 0x11;
        this->aics[aicIndex].poleturnerSetting = 0x13;
        this->aics[aicIndex].sellResource09 = 0x12;
        this->aics[aicIndex].sellResource10 = 0x13;
        this->aics[aicIndex].sellResource11 = 0x14;
        this->aics[aicIndex].sellResource12 = 0x15;
        this->aics[aicIndex].sellResource13 = 0x16;
        this->aics[aicIndex].sellResource14 = 0x17;
        this->aics[aicIndex].sellResource15 = 0x18;
        this->aics[aicIndex].defWallPatrolRallyTime = 2;
        this->aics[aicIndex].defWallPatrolGroups = 3;
        this->aics[aicIndex].defSiegeEngineGoldThreshold = 100;
        this->aics[aicIndex].defSiegeEngineBuildDelay = 4;
        this->aics[aicIndex].unknown072 = 200;
        this->aics[aicIndex].unknown073 = 0x14;
        this->aics[aicIndex].recruitProbDefDefault = 0x28;
        this->aics[aicIndex].recruitProbDefWeak = 0x50;
        this->aics[aicIndex].recruitProbDefStrong = 0x14;
        this->aics[aicIndex].recruitProbRaidDefault = 0x14;
        this->aics[aicIndex].recruitProbRaidWeak = 10;
        this->aics[aicIndex].recruitProbRaidStrong = 0x1e;
        this->aics[aicIndex].recruitProbAttackDefault = 0x28;
        this->aics[aicIndex].recruitProbAttackWeak = 10;
        this->aics[aicIndex].recruitProbAttackStrong = 0x32;
        this->aics[aicIndex].SortieUnitRangedMin = 4;
        this->aics[aicIndex].SortieUnitRanged = 0x46;
        this->aics[aicIndex].SortieUnitMeleeMin = 0x14;
        this->aics[aicIndex].SortieUnitMelee = 0x4b;
        this->aics[aicIndex].DefDiggingUnitMax = 4;
        this->aics[aicIndex].DefDiggingUnit = 0x16;
        this->aics[aicIndex].RecruitInterval = 0;
        this->aics[aicIndex].RecruitIntervalWeak = 1;
        this->aics[aicIndex].RecruitIntervalStrong = 0;
        this->aics[aicIndex].DefTotal = 0x32;
        this->aics[aicIndex].OuterPatrolGroupsCount = 1;
        this->aics[aicIndex].OuterPatrolGroupsMove = 1;
        this->aics[aicIndex].OuterPatrolRallyDelay = 2;
        this->aics[aicIndex].DefWalls = 0x32;
        this->aics[aicIndex].DefUnit1 = 0x16;
        this->aics[aicIndex].DefUnit2 = 0x46;
        this->aics[aicIndex].RaidUnitsBase = 0x1e;
        this->aics[aicIndex].RaidUnitsRandom = 10;
        this->aics[aicIndex].RaidUnit1 = 0x4b;
        this->aics[aicIndex].HarassingSiegeEngine1 = 0xbe;
        this->aics[aicIndex].HarassingSiegeEngine2 = 0xbe;
        this->aics[aicIndex].HarassingSiegeEngine3 = 0x166;
        this->aics[aicIndex].HarassingSiegeEnginesMax = 3;
        this->aics[aicIndex].RaidRetargetDelay = 4;
        this->aics[aicIndex].AttForceBase = 0x1e;
        this->aics[aicIndex].AttForceRandom = 10;
        this->aics[aicIndex].AttForceSupportAllyThreshold = 0x14;
        this->aics[aicIndex].AttForceRallyPercentage = 0x50;
        this->aics[aicIndex].AttMovingTribesThreshold = 100;
        this->aics[aicIndex].AttAssaultDelay = 0;
        this->aics[aicIndex].AttUnitPatrolRecommandDelay = 5;
        this->aics[aicIndex].AttCoordinationPreference = 0x50;
        this->aics[aicIndex].SiegeEngine1 = 0x27;
        this->aics[aicIndex].SiegeEngine2 = 0x27;
        this->aics[aicIndex].SiegeEngine3 = 0x3d;
        this->aics[aicIndex].CowThrowInterval = 10000;
        this->aics[aicIndex].AttMaxEngineers = 6;
        this->aics[aicIndex].AttDiggingUnit = 0x16;
        this->aics[aicIndex].AttDiggingUnitMax = 0xf;
        this->aics[aicIndex].AttUnit2 = 0;
        this->aics[aicIndex].AttUnit2Max = 0;
        this->aics[aicIndex].AttMaxAssassins = 0;
        this->aics[aicIndex].AttMaxLaddermen = 0;
        this->aics[aicIndex].AttMaxTunnelers = 0;
        this->aics[aicIndex].AttUnitPatrol = 0;
        this->aics[aicIndex].AttUnitPatrolMax = 0;
        this->aics[aicIndex].AttUnitPatrolGroupsCount = 0;
        this->aics[aicIndex].AttUnitBackup = 0x4a;
        this->aics[aicIndex].AttUnitBackupMax = 0x50;
        this->aics[aicIndex].AttUnitBackupGroupsCount = 1;
        this->aics[aicIndex].AttUnitEngage = 0;
        this->aics[aicIndex].AttUnitEngageMax = 0;
        this->aics[aicIndex].AttUnitSiegeDef = 0;
        this->aics[aicIndex].AttUnitSiegeDefMax = 0;
        this->aics[aicIndex].AttUnitSiegeDefGroupsCount = 0;
        this->aics[aicIndex].AttUnitMain1 = 0x4b;
        this->aics[aicIndex].AttMaxDefault = 200;
        this->aics[aicIndex].AttMainGroupsCount = 2;
        this->aics[aicIndex].TargetChoice = OpenSHC::AI::AIC::AITC_GOLD;
    }

}
}
