#include "../AICState.func.hpp"
#include "OpenSHC/AI/AIC/AITargetChoice.hpp"

namespace OpenSHC {
namespace AI {

    using OpenSHC::AI::AIC::AITargetChoice;

    // FUNCTION: STRONGHOLDCRUSADER 0x004C9120
    void AICState::setAICParameters_10(int aicIndex)
    {
        this->aics[aicIndex].flagType = 0xd;
        this->aics[aicIndex].unknown001 = 0;
        this->aics[aicIndex].unknown002 = 0;
        this->aics[aicIndex].unknown003 = 0;
        this->aics[aicIndex].unknown004 = 1;
        this->aics[aicIndex].unknown005 = 1;
        this->aics[aicIndex].criticalPopularity = 4000;
        this->aics[aicIndex].lowestPopularity = 5000;
        this->aics[aicIndex].highestPopularity = 8000;
        this->aics[aicIndex].taxesMin = 2;
        this->aics[aicIndex].taxesMax = 10;
        this->aics[aicIndex].unknown011 = 10;
        this->aics[aicIndex].farm1 = 0x20;
        this->aics[aicIndex].farm2 = 0x20;
        this->aics[aicIndex].populationPerFarm = 5;
        this->aics[aicIndex].populationPerWoodcutter = 7;
        this->aics[aicIndex].populationPerQuarry = 0;
        this->aics[aicIndex].populationPerIronmine = 7;
        this->aics[aicIndex].populationPerPitchrig = 0;
        this->aics[aicIndex].maxQuarries = 1;
        this->aics[aicIndex].maxIronmines = 3;
        this->aics[aicIndex].maxWoodcutters = 10;
        this->aics[aicIndex].maxPitchrigs = 1;
        this->aics[aicIndex].maxFarms = 8;
        this->aics[aicIndex].buildInterval = 4;
        this->aics[aicIndex].resourceRebuildDelay = 0x3c;
        this->aics[aicIndex].maxFood = 100;
        this->aics[aicIndex].minimumApples = 10;
        this->aics[aicIndex].minimumCheese = 10;
        this->aics[aicIndex].minimumBread = 10;
        this->aics[aicIndex].minimumWheat = -1;
        this->aics[aicIndex].minimumHop = -1;
        this->aics[aicIndex].tradeAmountFood = 0x14;
        this->aics[aicIndex].tradeAmountEquipment = 2;
        this->aics[aicIndex].aiRequestDelay = 0xc;
        this->aics[aicIndex].minimumGoodsRequiredAfterTrade = 10;
        this->aics[aicIndex].doubleRationsFoodThreshold = 0x32;
        this->aics[aicIndex].maxWood = 0x3c;
        this->aics[aicIndex].maxStone = 0x3c;
        this->aics[aicIndex].maxResourceOther = 0xf;
        this->aics[aicIndex].maxEquipment = 6;
        this->aics[aicIndex].maxBeer = 10;
        this->aics[aicIndex].maxResourceVariance = 4;
        this->aics[aicIndex].recruitGoldThreshold = 200;
        this->aics[aicIndex].blacksmithSetting = 0x16;
        this->aics[aicIndex].fletcherSetting = 0x11;
        this->aics[aicIndex].poleturnerSetting = 0x13;
        this->aics[aicIndex].sellResource02 = 3;
        this->aics[aicIndex].sellResource04 = 7;
        this->aics[aicIndex].sellResource05 = 9;
        this->aics[aicIndex].sellResource06 = 0xe;
        this->aics[aicIndex].sellResource07 = 0x10;
        this->aics[aicIndex].sellResource09 = 0x12;
        this->aics[aicIndex].sellResource11 = 0x14;
        this->aics[aicIndex].sellResource12 = 0x15;
        this->aics[aicIndex].sellResource14 = 0x17;
        this->aics[aicIndex].defWallPatrolRallyTime = 2;
        this->aics[aicIndex].defWallPatrolGroups = 3;
        this->aics[aicIndex].defSiegeEngineGoldThreshold = 100;
        this->aics[aicIndex].defSiegeEngineBuildDelay = 4;
        this->aics[aicIndex].unknown072 = 200;
        this->aics[aicIndex].unknown073 = 0x14;
        this->aics[aicIndex].recruitProbDefDefault = 0x28;
        this->aics[aicIndex].recruitProbDefWeak = 0x46;
        this->aics[aicIndex].recruitProbDefStrong = 0x14;
        this->aics[aicIndex].recruitProbRaidDefault = 0x28;
        this->aics[aicIndex].recruitProbRaidWeak = 0x14;
        this->aics[aicIndex].recruitProbRaidStrong = 0x14;
        this->aics[aicIndex].recruitProbAttackDefault = 0x14;
        this->aics[aicIndex].recruitProbAttackWeak = 10;
        this->aics[aicIndex].recruitProbAttackStrong = 0x3c;
        this->aics[aicIndex].SortieUnitRangedMin = 2;
        this->aics[aicIndex].SortieUnitRanged = 0x16;
        this->aics[aicIndex].SortieUnitMeleeMin = 0x14;
        this->aics[aicIndex].SortieUnitMelee = 0x18;
        this->aics[aicIndex].DefDiggingUnitMax = 4;
        this->aics[aicIndex].DefDiggingUnit = 0x18;
        this->aics[aicIndex].RecruitInterval = 4;
        this->aics[aicIndex].RecruitIntervalWeak = 4;
        this->aics[aicIndex].RecruitIntervalStrong = 4;
        this->aics[aicIndex].DefTotal = 0x14;
        this->aics[aicIndex].OuterPatrolGroupsCount = 4;
        this->aics[aicIndex].OuterPatrolGroupsMove = 1;
        this->aics[aicIndex].OuterPatrolRallyDelay = 2;
        this->aics[aicIndex].DefWalls = 4;
        this->aics[aicIndex].DefUnit1 = 0x1c;
        this->aics[aicIndex].DefUnit2 = 0x16;
        this->aics[aicIndex].DefUnit3 = 0x16;
        this->aics[aicIndex].DefUnit4 = 0x16;
        this->aics[aicIndex].DefUnit5 = 0x16;
        this->aics[aicIndex].DefUnit6 = 0x16;
        this->aics[aicIndex].RaidUnitsBase = 4;
        this->aics[aicIndex].RaidUnitsRandom = 4;
        this->aics[aicIndex].RaidUnit1 = 0x1c;
        this->aics[aicIndex].HarassingSiegeEngine1 = 0xbe;
        this->aics[aicIndex].HarassingSiegeEnginesMax = 1;
        this->aics[aicIndex].RaidRetargetDelay = 4;
        this->aics[aicIndex].AttForceBase = 10;
        this->aics[aicIndex].AttForceRandom = 0x14;
        this->aics[aicIndex].AttForceSupportAllyThreshold = 0x28;
        this->aics[aicIndex].AttForceRallyPercentage = 0x28;
        this->aics[aicIndex].AttMovingTribesThreshold = 100;
        this->aics[aicIndex].AttAssaultDelay = 0;
        this->aics[aicIndex].AttUnitPatrolRecommandDelay = 5;
        this->aics[aicIndex].AttCoordinationPreference = 0x46;
        this->aics[aicIndex].SiegeEngine1 = 0;
        this->aics[aicIndex].CowThrowInterval = 10000;
        this->aics[aicIndex].AttMaxEngineers = 0;
        this->aics[aicIndex].AttDiggingUnit = 0x18;
        this->aics[aicIndex].AttDiggingUnitMax = 0x3c;
        this->aics[aicIndex].AttUnit2 = 0;
        this->aics[aicIndex].AttUnit2Max = 0x18;
        this->aics[aicIndex].AttMaxAssassins = 0;
        this->aics[aicIndex].AttMaxLaddermen = 0;
        this->aics[aicIndex].AttMaxTunnelers = 0;
        this->aics[aicIndex].AttUnitPatrol = 0;
        this->aics[aicIndex].AttUnitPatrolMax = 0;
        this->aics[aicIndex].AttUnitPatrolGroupsCount = 0;
        this->aics[aicIndex].AttUnitBackup = 0;
        this->aics[aicIndex].AttUnitBackupMax = 0;
        this->aics[aicIndex].AttUnitBackupGroupsCount = 0;
        this->aics[aicIndex].AttUnitEngage = 0;
        this->aics[aicIndex].AttUnitEngageMax = 0;
        this->aics[aicIndex].AttUnitSiegeDef = 0;
        this->aics[aicIndex].AttUnitSiegeDefMax = 0;
        this->aics[aicIndex].AttUnitSiegeDefGroupsCount = 0;
        this->aics[aicIndex].AttUnitMain1 = 0x18;
        this->aics[aicIndex].AttUnitMain2 = 0x18;
        this->aics[aicIndex].AttMaxDefault = 200;
        this->aics[aicIndex].AttMainGroupsCount = 2;
        this->aics[aicIndex].TargetChoice = OpenSHC::AI::AIC::AITC_BALANCED;
    }

}
}
