#include "OpenSHC/AI/AIC/AITargetChoice.hpp"
#include "OpenSHC/AI/AICState.hpp"

namespace OpenSHC {
namespace AI {

    using AIC::AITC_ANY;
    using AIC::AITC_BALANCED;
    using AIC::AITC_CLOSEST;
    using AIC::AITC_GOLD;
    using AIC::AITC_PLAYER;

    // FUNCTION: STRONGHOLDCRUSADER 0x004C6D60
    void AICState::setAICParameters_01(int aicID)
    {
        this->aics[aicID].populationPerFarm = 6;
        this->aics[aicID].minimumCheese = 0xffffffff;
        this->aics[aicID].minimumBread = 0xffffffff;
        this->aics[aicID].minimumWheat = 0xffffffff;
        this->aics[aicID].minimumHop = 0xffffffff;
        this->aics[aicID].aiRequestDelay = 0x12;
        this->aics[aicID].populationPerQuarry = 0x12;
        this->aics[aicID].maxWoodcutters = 6;
        this->aics[aicID].maxFarms = 6;
        this->aics[aicID].sellResource09 = 0x12;
        this->aics[aicID].flagType = 0xc;
        this->aics[aicID].unknown002 = 0;
        this->aics[aicID].unknown001 = 0;
        this->aics[aicID].unknown003 = 0;
        this->aics[aicID].unknown004 = 0;
        this->aics[aicID].unknown005 = 0;
        this->aics[aicID].criticalPopularity = 4000;
        this->aics[aicID].lowestPopularity = 0x157c;
        this->aics[aicID].highestPopularity = 0x1d4c;
        this->aics[aicID].taxesMin = 3;
        this->aics[aicID].taxesMax = 10;
        this->aics[aicID].farm1 = 0x20;
        this->aics[aicID].unknown011 = 0x14;
        this->aics[aicID].maxFood = 100;
        this->aics[aicID].minimumApples = 10;
        this->aics[aicID].tradeAmountFood = 10;
        this->aics[aicID].tradeAmountEquipment = 2;
        this->aics[aicID].minimumGoodsRequiredAfterTrade = 0;
        this->aics[aicID].doubleRationsFoodThreshold = 0;
        this->aics[aicID].maxWood = 0x1e;
        this->aics[aicID].maxStone = 0x28;
        this->aics[aicID].maxResourceOther = 0x14;
        this->aics[aicID].maxEquipment = 0x14;
        this->aics[aicID].maxBeer = 0x14;
        this->aics[aicID].maxResourceVariance = 5;
        this->aics[aicID].recruitGoldThreshold = 200;
        this->aics[aicID].populationPerWoodcutter = 8;
        this->aics[aicID].populationPerIronmine = 0;
        this->aics[aicID].populationPerPitchrig = 0;
        this->aics[aicID].maxQuarries = 1;
        this->aics[aicID].maxIronmines = 1;
        this->aics[aicID].maxPitchrigs = 1;
        this->aics[aicID].buildInterval = 1;
        this->aics[aicID].resourceRebuildDelay = 10;
        this->aics[aicID].blacksmithSetting = 0x16;
        this->aics[aicID].fletcherSetting = 0x11;
        this->aics[aicID].poleturnerSetting = 0x13;
        this->aics[aicID].sellResource02 = 3;
        this->aics[aicID].sellResource03 = 6;
        this->aics[aicID].sellResource04 = 7;
        this->aics[aicID].sellResource05 = 9;
        this->aics[aicID].sellResource06 = 0xe;
        this->aics[aicID].sellResource07 = 0x10;
        this->aics[aicID].sellResource11 = 0x14;
        this->aics[aicID].sellResource12 = 0x15;
        this->aics[aicID].sellResource13 = 0x16;
        this->aics[aicID].sellResource14 = 0x17;
        this->aics[aicID].sellResource15 = 0x18;
        this->aics[aicID].defWallPatrolRallyTime = 0x14;
        this->aics[aicID].defWallPatrolGroups = 1;
        this->aics[aicID].defSiegeEngineGoldThreshold = 200;
        this->aics[aicID].defSiegeEngineBuildDelay = 0x14;
        this->aics[aicID].unknown072 = 800;
        this->aics[aicID].unknown073 = 0x50;
        this->aics[aicID].recruitProbDefWeak = 0x32;
        this->aics[aicID].RecruitIntervalWeak = 1;
        this->aics[aicID].RecruitInterval = 1;
        this->aics[aicID].RecruitIntervalStrong = 1;
        this->aics[aicID].SortieUnitRanged = 0x16;
        this->aics[aicID].SortieUnitMelee = 0x18;
        this->aics[aicID].DefDiggingUnit = 0x18;
        this->aics[aicID].OuterPatrolGroupsCount = 1;
        this->aics[aicID].OuterPatrolRallyDelay = 10;
        this->aics[aicID].DefUnit1 = 0x18;
        this->aics[aicID].DefUnit2 = 0x18;
        this->aics[aicID].DefUnit3 = 0x16;
        this->aics[aicID].DefUnit4 = 0x16;
        this->aics[aicID].RaidUnitsBase = 10;
        this->aics[aicID].RaidUnit1 = 0x18;
        this->aics[aicID].RaidUnit2 = 0x18;
        this->aics[aicID].RaidUnit3 = 0x16;
        this->aics[aicID].recruitProbDefDefault = 0;
        this->aics[aicID].recruitProbDefStrong = 0;
        this->aics[aicID].recruitProbRaidWeak = 0x32;
        this->aics[aicID].recruitProbRaidDefault = 0x32;
        this->aics[aicID].recruitProbRaidStrong = 0;
        this->aics[aicID].recruitProbAttackWeak = 0;
        this->aics[aicID].recruitProbAttackDefault = 0x32;
        this->aics[aicID].recruitProbAttackStrong = 100;
        this->aics[aicID].SortieUnitRangedMin = 5;
        this->aics[aicID].SortieUnitMeleeMin = 6;
        this->aics[aicID].DefDiggingUnitMax = 0;
        this->aics[aicID].DefWalls = 0x14;
        this->aics[aicID].DefTotal = 0x1e;
        this->aics[aicID].OuterPatrolGroupsMove = 0;
        this->aics[aicID].RaidUnitsRandom = 0xf;
        this->aics[aicID].HarassingSiegeEnginesMax = 0;
        this->aics[aicID].HarassingSiegeEngine1 = 0xbe;
        this->aics[aicID].RaidRetargetDelay = 3;
        this->aics[aicID].AttForceBase = 0x14;
        this->aics[aicID].AttForceRandom = 10;
        this->aics[aicID].AttForceSupportAllyThreshold = 0xf;
        this->aics[aicID].AttForceRallyPercentage = 0x32;
        this->aics[aicID].AttMovingTribesThreshold = 100;
        this->aics[aicID].AttAssaultDelay = 0;
        this->aics[aicID].AttUnitPatrolRecommandDelay = 0x19;
        this->aics[aicID].AttCoordinationPreference = 0x14;
        this->aics[aicID].SiegeEngine1 = 0;
        this->aics[aicID].CowThrowInterval = 1000;
        this->aics[aicID].AttMaxEngineers = 0;
        this->aics[aicID].AttDiggingUnit = 0x18;
        this->aics[aicID].AttDiggingUnitMax = 0x14;
        this->aics[aicID].AttMaxAssassins = 0;
        this->aics[aicID].AttUnit2 = 0x16;
        this->aics[aicID].AttUnit2Max = 0;
        this->aics[aicID].AttMaxLaddermen = 0;
        this->aics[aicID].AttMaxTunnelers = 0;
        this->aics[aicID].AttUnitPatrol = 0x16;
        this->aics[aicID].AttUnitPatrolMax = 0;
        this->aics[aicID].AttUnitPatrolGroupsCount = 0;
        this->aics[aicID].AttUnitBackup = 0x16;
        this->aics[aicID].AttUnitBackupMax = 0x10;
        this->aics[aicID].AttUnitBackupGroupsCount = 0;
        this->aics[aicID].AttUnitEngageMax = 0;
        this->aics[aicID].AttUnitEngage = 0;
        this->aics[aicID].AttUnitSiegeDef = 0x18;
        this->aics[aicID].AttUnitSiegeDefMax = 0;
        this->aics[aicID].AttUnitSiegeDefGroupsCount = 0;
        this->aics[aicID].AttUnitMain1 = 0x18;
        this->aics[aicID].AttMaxDefault = 200;
        this->aics[aicID].AttMainGroupsCount = 1;
        this->aics[aicID].TargetChoice = AITC_PLAYER;
    }
}
}
