#include "OpenSHC/AI/AIC/AITargetChoice.hpp"
#include "OpenSHC/AI/AICState.hpp"

namespace OpenSHC {
namespace AI {

    using AIC::AITC_ANY;
    using AIC::AITC_BALANCED;
    using AIC::AITC_CLOSEST;
    using AIC::AITC_GOLD;
    using AIC::AITC_PLAYER;

    // FUNCTION: STRONGHOLDCRUSADER 0x004C7120
    void AICState::setAICParameters_02(int aicIndex)
    {
        this->aics[aicIndex].minimumBread = 0xffffffff;
        this->aics[aicIndex].minimumWheat = 0xffffffff;
        this->aics[aicIndex].minimumHop = 0xffffffff;
        this->aics[aicIndex].populationPerFarm = 5;
        this->aics[aicIndex].unknown011 = 0xf;
        this->aics[aicIndex].tradeAmountFood = 5;
        this->aics[aicIndex].aiRequestDelay = 0xc;
        this->aics[aicIndex].maxResourceOther = 0xf;
        this->aics[aicIndex].maxEquipment = 0xc;
        this->aics[aicIndex].maxBeer = 5;
        this->aics[aicIndex].maxResourceVariance = 5;
        this->aics[aicIndex].populationPerWoodcutter = 5;
        this->aics[aicIndex].populationPerQuarry = 0xf;
        this->aics[aicIndex].resourceRebuildDelay = 0xc;
        this->aics[aicIndex].flagType = 0xc;
        this->aics[aicIndex].unknown002 = 0;
        this->aics[aicIndex].unknown001 = 0;
        this->aics[aicIndex].unknown003 = 0;
        this->aics[aicIndex].unknown004 = 0;
        this->aics[aicIndex].unknown005 = 0;
        this->aics[aicIndex].criticalPopularity = 4000;
        this->aics[aicIndex].lowestPopularity = 5000;
        this->aics[aicIndex].highestPopularity = 8000;
        this->aics[aicIndex].taxesMin = 3;
        this->aics[aicIndex].taxesMax = 0xb;
        this->aics[aicIndex].farm1 = 0x20;
        this->aics[aicIndex].maxFood = 0x96;
        this->aics[aicIndex].minimumApples = 10;
        this->aics[aicIndex].minimumCheese = 0x14;
        this->aics[aicIndex].tradeAmountEquipment = 6;
        this->aics[aicIndex].minimumGoodsRequiredAfterTrade = 10;
        this->aics[aicIndex].doubleRationsFoodThreshold = 0x50;
        this->aics[aicIndex].maxWood = 0x30;
        this->aics[aicIndex].maxStone = 0x28;
        this->aics[aicIndex].recruitGoldThreshold = 200;
        this->aics[aicIndex].populationPerIronmine = 0;
        this->aics[aicIndex].populationPerPitchrig = 0;
        this->aics[aicIndex].maxQuarries = 2;
        this->aics[aicIndex].maxIronmines = 1;
        this->aics[aicIndex].maxWoodcutters = 10;
        this->aics[aicIndex].maxPitchrigs = 1;
        this->aics[aicIndex].maxFarms = 10;
        this->aics[aicIndex].buildInterval = 2;
        this->aics[aicIndex].blacksmithSetting = 0x16;
        this->aics[aicIndex].fletcherSetting = 0x11;
        this->aics[aicIndex].poleturnerSetting = 0x13;
        this->aics[aicIndex].sellResource02 = 3;
        this->aics[aicIndex].sellResource03 = 6;
        this->aics[aicIndex].sellResource04 = 7;
        this->aics[aicIndex].sellResource05 = 9;
        this->aics[aicIndex].sellResource06 = 0xe;
        this->aics[aicIndex].sellResource07 = 0x10;
        this->aics[aicIndex].sellResource09 = 0x12;
        this->aics[aicIndex].sellResource11 = 0x14;
        this->aics[aicIndex].sellResource12 = 0x15;
        this->aics[aicIndex].sellResource13 = 0x16;
        this->aics[aicIndex].sellResource14 = 0x17;
        this->aics[aicIndex].sellResource15 = 0x18;
        this->aics[aicIndex].defWallPatrolRallyTime = 2;
        this->aics[aicIndex].defWallPatrolGroups = 4;
        this->aics[aicIndex].defSiegeEngineGoldThreshold = 500;
        this->aics[aicIndex].defSiegeEngineBuildDelay = 0x14;
        this->aics[aicIndex].unknown072 = 400;
        this->aics[aicIndex].unknown073 = 0x3c;
        this->aics[aicIndex].recruitProbDefStrong = 0x14;
        this->aics[aicIndex].SortieUnitRanged = 0x16;
        this->aics[aicIndex].DefDiggingUnitMax = 0x14;
        this->aics[aicIndex].DefUnit1 = 0x16;
        this->aics[aicIndex].RaidUnitsRandom = 10;
        this->aics[aicIndex].recruitProbDefWeak = 0x46;
        this->aics[aicIndex].recruitProbRaidDefault = 0x28;
        this->aics[aicIndex].recruitProbRaidStrong = 0x28;
        this->aics[aicIndex].recruitProbAttackWeak = 0;
        this->aics[aicIndex].recruitProbAttackStrong = 0x28;
        this->aics[aicIndex].RecruitIntervalWeak = 0;
        this->aics[aicIndex].RecruitInterval = 1;
        this->aics[aicIndex].RecruitIntervalStrong = 1;
        this->aics[aicIndex].SortieUnitRangedMin = 2;
        this->aics[aicIndex].SortieUnitMeleeMin = 8;
        this->aics[aicIndex].SortieUnitMelee = 0x18;
        this->aics[aicIndex].DefDiggingUnit = 0x18;
        this->aics[aicIndex].DefWalls = 0x32;
        this->aics[aicIndex].DefTotal = 0x50;
        this->aics[aicIndex].OuterPatrolGroupsCount = 3;
        this->aics[aicIndex].OuterPatrolGroupsMove = 1;
        this->aics[aicIndex].OuterPatrolRallyDelay = 2;
        this->aics[aicIndex].RaidUnit1 = 0x47;
        this->aics[aicIndex].RaidUnit2 = 0x47;
        this->aics[aicIndex].RaidUnit3 = 0x47;
        this->aics[aicIndex].RaidUnit4 = 0x48;
        this->aics[aicIndex].HarassingSiegeEnginesMax = 1;
        this->aics[aicIndex].HarassingSiegeEngine1 = 0xbe;
        this->aics[aicIndex].recruitProbDefDefault = 0x1e;
        this->aics[aicIndex].recruitProbRaidWeak = 0x1e;
        this->aics[aicIndex].recruitProbAttackDefault = 0x1e;
        this->aics[aicIndex].RaidUnitsBase = 0x1e;
        this->aics[aicIndex].RaidRetargetDelay = 3;
        this->aics[aicIndex].AttForceBase = 0x1e;
        this->aics[aicIndex].AttForceRandom = 10;
        this->aics[aicIndex].AttForceSupportAllyThreshold = 0x1e;
        this->aics[aicIndex].AttForceRallyPercentage = 0x32;
        this->aics[aicIndex].AttMovingTribesThreshold = 100;
        this->aics[aicIndex].AttAssaultDelay = 0;
        this->aics[aicIndex].AttUnitPatrolRecommandDelay = 0x19;
        this->aics[aicIndex].AttCoordinationPreference = 0x28;
        this->aics[aicIndex].SiegeEngine1 = 0x27;
        this->aics[aicIndex].CowThrowInterval = 1000;
        this->aics[aicIndex].AttMaxEngineers = 2;
        this->aics[aicIndex].AttDiggingUnit = 0x18;
        this->aics[aicIndex].AttDiggingUnitMax = 0x14;
        this->aics[aicIndex].AttMaxAssassins = 0;
        this->aics[aicIndex].AttUnit2 = 0x16;
        this->aics[aicIndex].AttUnit2Max = 0x14;
        this->aics[aicIndex].AttMaxLaddermen = 10;
        this->aics[aicIndex].AttMaxTunnelers = 0;
        this->aics[aicIndex].AttUnitPatrol = 0x48;
        this->aics[aicIndex].AttUnitPatrolMax = 0;
        this->aics[aicIndex].AttUnitPatrolGroupsCount = 0;
        this->aics[aicIndex].AttUnitBackup = 0x46;
        this->aics[aicIndex].AttUnitBackupMax = 0x32;
        this->aics[aicIndex].AttUnitBackupGroupsCount = 1;
        this->aics[aicIndex].AttUnitEngageMax = 0;
        this->aics[aicIndex].AttUnitEngage = 0;
        this->aics[aicIndex].AttUnitSiegeDef = 0x16;
        this->aics[aicIndex].AttUnitSiegeDefMax = 0x1e;
        this->aics[aicIndex].AttUnitSiegeDefGroupsCount = 0;
        this->aics[aicIndex].AttUnitMain1 = 0x18;
        this->aics[aicIndex].AttMaxDefault = 200;
        this->aics[aicIndex].AttMainGroupsCount = 1;
        this->aics[aicIndex].TargetChoice = AITC_BALANCED;
    }
}
}
