#include "../AICState.func.hpp"

#include "OpenSHC/AI/AIC/AITargetChoice.hpp"

namespace OpenSHC {
namespace AI {

    using OpenSHC::AI::AIC::AITargetChoice;

    // FUNCTION: STRONGHOLDCRUSADER 0x004C8110
    void AICState::setAICParameters_06(int aicIndex)
    {
        this->aics[aicIndex].minimumCheese = -1;
        this->aics[aicIndex].minimumBread = -1;
        this->aics[aicIndex].minimumWheat = -1;
        this->aics[aicIndex].minimumHop = -1;
        this->aics[aicIndex].taxesMax = 0xc;
        this->aics[aicIndex].farm1 = 0x20;
        this->aics[aicIndex].farm3 = 0x20;
        this->aics[aicIndex].unknown011 = 0xc;
        this->aics[aicIndex].aiRequestDelay = 0xc;
        this->aics[aicIndex].minimumGoodsRequiredAfterTrade = 0x32;
        this->aics[aicIndex].doubleRationsFoodThreshold = 0x32;
        this->aics[aicIndex].maxWood = 0x32;
        this->aics[aicIndex].maxStone = 0x32;
        this->aics[aicIndex].populationPerIronmine = 0xc;
        this->aics[aicIndex].flagType = 10;
        this->aics[aicIndex].unknown002 = 0;
        this->aics[aicIndex].unknown001 = 0;
        this->aics[aicIndex].unknown003 = 0;
        this->aics[aicIndex].unknown004 = 0;
        this->aics[aicIndex].unknown005 = 1;
        this->aics[aicIndex].criticalPopularity = 4000;
        this->aics[aicIndex].lowestPopularity = 5000;
        this->aics[aicIndex].highestPopularity = 9000;
        this->aics[aicIndex].taxesMin = 3;
        this->aics[aicIndex].farm2 = 0x1f;
        this->aics[aicIndex].populationPerFarm = 5;
        this->aics[aicIndex].maxFood = 100;
        this->aics[aicIndex].minimumApples = 10;
        this->aics[aicIndex].tradeAmountFood = 10;
        this->aics[aicIndex].tradeAmountEquipment = 0;
        this->aics[aicIndex].maxResourceOther = 10;
        this->aics[aicIndex].maxEquipment = 5;
        this->aics[aicIndex].maxBeer = 0xf;
        this->aics[aicIndex].maxResourceVariance = 5;
        this->aics[aicIndex].recruitGoldThreshold = 200;
        this->aics[aicIndex].populationPerWoodcutter = 7;
        this->aics[aicIndex].populationPerQuarry = 10;
        this->aics[aicIndex].populationPerPitchrig = 7;
        this->aics[aicIndex].maxQuarries = 2;
        this->aics[aicIndex].maxIronmines = 1;
        this->aics[aicIndex].maxWoodcutters = 8;
        this->aics[aicIndex].maxPitchrigs = 10;
        this->aics[aicIndex].maxFarms = 10;
        this->aics[aicIndex].buildInterval = 3;
        this->aics[aicIndex].resourceRebuildDelay = 0x3c;
        this->aics[aicIndex].blacksmithSetting = 0x16;
        this->aics[aicIndex].fletcherSetting = 0x12;
        this->aics[aicIndex].poleturnerSetting = 0x14;
        this->aics[aicIndex].defWallPatrolRallyTime = 5;
        this->aics[aicIndex].defWallPatrolGroups = 2;
        this->aics[aicIndex].defSiegeEngineGoldThreshold = 0x78;
        this->aics[aicIndex].defSiegeEngineBuildDelay = 8;
        this->aics[aicIndex].sellResource03 = 6;
        this->aics[aicIndex].sellResource05 = 9;
        this->aics[aicIndex].sellResource07 = 0x10;
        this->aics[aicIndex].sellResource08 = 0x11;
        this->aics[aicIndex].sellResource09 = 0x12;
        this->aics[aicIndex].sellResource10 = 0x13;
        this->aics[aicIndex].sellResource11 = 0x14;
        this->aics[aicIndex].sellResource12 = 0x15;
        this->aics[aicIndex].sellResource13 = 0x16;
        this->aics[aicIndex].sellResource14 = 0x17;
        this->aics[aicIndex].sellResource15 = 0x18;
        this->aics[aicIndex].unknown072 = 100;
        this->aics[aicIndex].unknown073 = 0x14;
        this->aics[aicIndex].recruitProbRaidWeak = 0x14;
        this->aics[aicIndex].recruitProbAttackDefault = 0x14;
        this->aics[aicIndex].recruitProbAttackWeak = 0;
        this->aics[aicIndex].RecruitInterval = 0;
        this->aics[aicIndex].RecruitIntervalStrong = 0;
        this->aics[aicIndex].SortieUnitRangedMin = 7;
        this->aics[aicIndex].SortieUnitMeleeMin = 5;
        this->aics[aicIndex].SortieUnitRanged = 0x46;
        this->aics[aicIndex].SortieUnitMelee = 0x4b;
        this->aics[aicIndex].OuterPatrolGroupsCount = 2;
        this->aics[aicIndex].HarassingSiegeEnginesMax = 2;
        this->aics[aicIndex].recruitProbDefWeak = 0x50;
        this->aics[aicIndex].recruitProbDefDefault = 0x28;
        this->aics[aicIndex].recruitProbDefStrong = 0x28;
        this->aics[aicIndex].recruitProbRaidDefault = 0x28;
        this->aics[aicIndex].recruitProbRaidStrong = 0x1e;
        this->aics[aicIndex].recruitProbAttackStrong = 0x1e;
        this->aics[aicIndex].RecruitIntervalWeak = 1;
        this->aics[aicIndex].DefDiggingUnitMax = 4;
        this->aics[aicIndex].DefDiggingUnit = 0x47;
        this->aics[aicIndex].DefWalls = 0x3c;
        this->aics[aicIndex].DefTotal = 0x3c;
        this->aics[aicIndex].OuterPatrolGroupsMove = 1;
        this->aics[aicIndex].OuterPatrolRallyDelay = 10;
        this->aics[aicIndex].DefUnit1 = 0x4c;
        this->aics[aicIndex].DefUnit2 = 0x46;
        this->aics[aicIndex].DefUnit3 = 0x46;
        this->aics[aicIndex].DefUnit4 = 0x46;
        this->aics[aicIndex].RaidUnitsBase = 0x1e;
        this->aics[aicIndex].RaidUnitsRandom = 0x1e;
        this->aics[aicIndex].RaidUnit1 = 0x47;
        this->aics[aicIndex].HarassingSiegeEngine1 = 0x166;
        this->aics[aicIndex].HarassingSiegeEngine2 = 0xbe;
        this->aics[aicIndex].RaidRetargetDelay = 3;
        this->aics[aicIndex].AttForceBase = 0xf;
        this->aics[aicIndex].AttForceRandom = 10;
        this->aics[aicIndex].AttForceSupportAllyThreshold = 0x46;
        this->aics[aicIndex].AttForceRallyPercentage = 100;
        this->aics[aicIndex].AttMovingTribesThreshold = 100;
        this->aics[aicIndex].AttAssaultDelay = 2;
        this->aics[aicIndex].AttUnitPatrolRecommandDelay = 10;
        this->aics[aicIndex].AttCoordinationPreference = 0x32;
        this->aics[aicIndex].CowThrowInterval = 7;
        this->aics[aicIndex].SiegeEngine1 = 0x4d;
        this->aics[aicIndex].SiegeEngine2 = 0x4d;
        this->aics[aicIndex].SiegeEngine3 = 0x4d;
        this->aics[aicIndex].AttMaxEngineers = 6;
        this->aics[aicIndex].AttDiggingUnit = 0x47;
        this->aics[aicIndex].AttDiggingUnitMax = 0x14;
        this->aics[aicIndex].AttMaxAssassins = 0;
        this->aics[aicIndex].AttUnit2 = 0x4b;
        this->aics[aicIndex].AttUnit2Max = 0;
        this->aics[aicIndex].AttMaxLaddermen = 0;
        this->aics[aicIndex].AttMaxTunnelers = 0;
        this->aics[aicIndex].AttUnitPatrol = 0x4a;
        this->aics[aicIndex].AttUnitPatrolMax = 0;
        this->aics[aicIndex].AttUnitPatrolGroupsCount = 0;
        this->aics[aicIndex].AttUnitBackup = 0x4a;
        this->aics[aicIndex].AttUnitBackupMax = 0x28;
        this->aics[aicIndex].AttUnitBackupGroupsCount = 2;
        this->aics[aicIndex].AttUnitEngageMax = 0;
        this->aics[aicIndex].AttUnitEngage = 0;
        this->aics[aicIndex].AttUnitSiegeDef = 0x46;
        this->aics[aicIndex].AttUnitSiegeDefMax = 10;
        this->aics[aicIndex].AttUnitSiegeDefGroupsCount = 1;
        this->aics[aicIndex].AttUnitMain1 = 0x4b;
        this->aics[aicIndex].AttMaxDefault = 200;
        this->aics[aicIndex].AttMainGroupsCount = 5;
        this->aics[aicIndex].TargetChoice = OpenSHC::AI::AIC::AITC_BALANCED;
    }

}
}
