#include "OpenSHC/AI/AIC/AITargetChoice.hpp"
#include "OpenSHC/AI/AICState.hpp"

namespace OpenSHC {
namespace AI {

    using AIC::AITC_ANY;
    using AIC::AITC_BALANCED;
    using AIC::AITC_CLOSEST;
    using AIC::AITC_GOLD;
    using AIC::AITC_PLAYER;

    // FUNCTION: STRONGHOLDCRUSADER 0x004C7910
    void AICState::setAICParameters_04(int aicIndex)
    {
        this->aics[aicIndex].unknown004 = 1;
        this->aics[aicIndex].unknown005 = 1;
        this->aics[aicIndex].farm2 = 0x20;
        this->aics[aicIndex].farm4 = 0x20;
        this->aics[aicIndex].minimumWheat = -1;
        this->aics[aicIndex].minimumHop = -1;
        this->aics[aicIndex].flagType = 0xd;
        this->aics[aicIndex].unknown002 = 0;
        this->aics[aicIndex].unknown001 = 0;
        this->aics[aicIndex].unknown003 = 0;
        this->aics[aicIndex].criticalPopularity = 0x1194;
        this->aics[aicIndex].lowestPopularity = 6000;
        this->aics[aicIndex].highestPopularity = 9000;
        this->aics[aicIndex].taxesMin = 3;
        this->aics[aicIndex].taxesMax = 0xb;
        this->aics[aicIndex].farm1 = 0x21;
        this->aics[aicIndex].farm3 = 0x1f;
        this->aics[aicIndex].populationPerFarm = 5;
        this->aics[aicIndex].unknown011 = 0xc;
        this->aics[aicIndex].maxFood = 200;
        this->aics[aicIndex].minimumApples = 5;
        this->aics[aicIndex].minimumCheese = 5;
        this->aics[aicIndex].minimumBread = 5;
        this->aics[aicIndex].tradeAmountFood = 10;
        this->aics[aicIndex].tradeAmountEquipment = 4;
        this->aics[aicIndex].aiRequestDelay = 0x14;
        this->aics[aicIndex].minimumGoodsRequiredAfterTrade = 0x28;
        this->aics[aicIndex].doubleRationsFoodThreshold = 0x1e;
        this->aics[aicIndex].maxWood = 0x3c;
        this->aics[aicIndex].maxStone = 0x32;
        this->aics[aicIndex].maxResourceOther = 10;
        this->aics[aicIndex].maxEquipment = 10;
        this->aics[aicIndex].maxBeer = 0xf;
        this->aics[aicIndex].maxResourceVariance = 5;
        this->aics[aicIndex].recruitGoldThreshold = 200;
        this->aics[aicIndex].populationPerWoodcutter = 4;
        this->aics[aicIndex].populationPerQuarry = 9;
        this->aics[aicIndex].populationPerIronmine = 0xd;
        this->aics[aicIndex].populationPerPitchrig = 0xf;
        this->aics[aicIndex].maxQuarries = 6;
        this->aics[aicIndex].maxIronmines = 3;
        this->aics[aicIndex].maxWoodcutters = 0xc;
        this->aics[aicIndex].maxPitchrigs = 2;
        this->aics[aicIndex].maxFarms = 10;
        this->aics[aicIndex].buildInterval = 3;
        this->aics[aicIndex].resourceRebuildDelay = 0x14;
        this->aics[aicIndex].blacksmithSetting = 0x16;
        this->aics[aicIndex].fletcherSetting = 0x12;
        this->aics[aicIndex].poleturnerSetting = 0x14;
        this->aics[aicIndex].sellResource05 = 9;
        this->aics[aicIndex].sellResource07 = 0x10;
        this->aics[aicIndex].sellResource10 = 0x13;
        this->aics[aicIndex].sellResource12 = 0x15;
        this->aics[aicIndex].defWallPatrolRallyTime = 4;
        this->aics[aicIndex].defWallPatrolGroups = 3;
        this->aics[aicIndex].defSiegeEngineGoldThreshold = 0xfa;
        this->aics[aicIndex].defSiegeEngineBuildDelay = 2;
        this->aics[aicIndex].unknown072 = 100;
        this->aics[aicIndex].unknown073 = 0x14;
        this->aics[aicIndex].recruitProbDefWeak = 0x5a;
        this->aics[aicIndex].recruitProbDefDefault = 0x3c;
        this->aics[aicIndex].recruitProbDefStrong = 0x1e;
        this->aics[aicIndex].recruitProbRaidWeak = 10;
        this->aics[aicIndex].recruitProbRaidDefault = 0x1e;
        this->aics[aicIndex].recruitProbRaidStrong = 10;
        this->aics[aicIndex].recruitProbAttackDefault = 10;
        this->aics[aicIndex].RecruitInterval = 4;
        this->aics[aicIndex].RecruitIntervalStrong = 4;
        this->aics[aicIndex].OuterPatrolGroupsCount = 4;
        this->aics[aicIndex].HarassingSiegeEnginesMax = 4;
        this->aics[aicIndex].recruitProbAttackWeak = 0;
        this->aics[aicIndex].OuterPatrolRallyDelay = 3;
        this->aics[aicIndex].RaidUnitsRandom = 0x14;
        this->aics[aicIndex].recruitProbAttackStrong = 0x3c;
        this->aics[aicIndex].RecruitIntervalWeak = 1;
        this->aics[aicIndex].SortieUnitRangedMin = 8;
        this->aics[aicIndex].SortieUnitRanged = 0x46;
        this->aics[aicIndex].SortieUnitMeleeMin = 6;
        this->aics[aicIndex].SortieUnitMelee = 0x19;
        this->aics[aicIndex].DefDiggingUnitMax = 8;
        this->aics[aicIndex].DefDiggingUnit = 0x19;
        this->aics[aicIndex].DefWalls = 0x50;
        this->aics[aicIndex].DefTotal = 100;
        this->aics[aicIndex].OuterPatrolGroupsMove = 1;
        this->aics[aicIndex].DefUnit1 = 0x17;
        this->aics[aicIndex].DefUnit2 = 0x17;
        this->aics[aicIndex].DefUnit3 = 0x16;
        this->aics[aicIndex].DefUnit4 = 0x16;
        this->aics[aicIndex].RaidUnitsBase = 5;
        this->aics[aicIndex].RaidUnit1 = 0x4a;
        this->aics[aicIndex].RaidUnit2 = 0x4a;
        this->aics[aicIndex].HarassingSiegeEngine1 = 0xbe;
        this->aics[aicIndex].RaidRetargetDelay = 5;
        this->aics[aicIndex].AttForceBase = 0x28;
        this->aics[aicIndex].AttForceRandom = 0xf;
        this->aics[aicIndex].AttForceSupportAllyThreshold = 0x1e;
        this->aics[aicIndex].AttForceRallyPercentage = 0x50;
        this->aics[aicIndex].AttMovingTribesThreshold = 100;
        this->aics[aicIndex].AttAssaultDelay = 0xc;
        this->aics[aicIndex].AttUnitPatrolRecommandDelay = 5;
        this->aics[aicIndex].AttCoordinationPreference = 0x32;
        this->aics[aicIndex].CowThrowInterval = 8;
        this->aics[aicIndex].SiegeEngine1 = 0x27;
        this->aics[aicIndex].SiegeEngine2 = 0x28;
        this->aics[aicIndex].SiegeEngine3 = 0x4d;
        this->aics[aicIndex].SiegeEngine4 = 0x28;
        this->aics[aicIndex].AttMaxEngineers = 0xc;
        this->aics[aicIndex].AttDiggingUnit = 0x19;
        this->aics[aicIndex].AttDiggingUnitMax = 0x14;
        this->aics[aicIndex].AttMaxAssassins = 0;
        this->aics[aicIndex].AttUnit2 = 0;
        this->aics[aicIndex].AttUnit2Max = 0;
        this->aics[aicIndex].AttMaxLaddermen = 0;
        this->aics[aicIndex].AttMaxTunnelers = 0;
        this->aics[aicIndex].AttUnitPatrol = 0;
        this->aics[aicIndex].AttUnitPatrolMax = 0;
        this->aics[aicIndex].AttUnitPatrolGroupsCount = 0;
        this->aics[aicIndex].AttUnitBackup = 0x17;
        this->aics[aicIndex].AttUnitBackupMax = 0x1e;
        this->aics[aicIndex].AttUnitBackupGroupsCount = 3;
        this->aics[aicIndex].AttUnitEngageMax = 0;
        this->aics[aicIndex].AttUnitEngage = 0;
        this->aics[aicIndex].AttUnitSiegeDef = 0x1b;
        this->aics[aicIndex].AttUnitSiegeDefMax = 5;
        this->aics[aicIndex].AttUnitSiegeDefGroupsCount = 1;
        this->aics[aicIndex].AttUnitMain1 = 0x1b;
        this->aics[aicIndex].AttUnitMain2 = 0x19;
        this->aics[aicIndex].AttUnitMain3 = 0x19;
        this->aics[aicIndex].AttMaxDefault = 200;
        this->aics[aicIndex].AttMainGroupsCount = 3;
        this->aics[aicIndex].TargetChoice = AITC_CLOSEST;
    }
}
}
