#include "OpenSHC/AI/AIC/AITargetChoice.hpp"
#include "OpenSHC/AI/AICState.hpp"

namespace OpenSHC {
namespace AI {

    using AIC::AITC_ANY;
    using AIC::AITC_BALANCED;
    using AIC::AITC_CLOSEST;
    using AIC::AITC_GOLD;
    using AIC::AITC_PLAYER;

    // FUNCTION: STRONGHOLDCRUSADER 0x004C7D20
    void AICState::setAICParameters_05(int param_1)
    {
        this->aics[param_1].maxFood = 0x32;
        this->aics[param_1].maxStone = 0x32;
        this->aics[param_1].taxesMin = 3;
        this->aics[param_1].taxesMax = 0xc;
        this->aics[param_1].farm2 = 0x1e;
        this->aics[param_1].farm3 = 0x1e;
        this->aics[param_1].populationPerFarm = 3;
        this->aics[param_1].populationPerIronmine = 0xc;
        this->aics[param_1].maxQuarries = 4;
        this->aics[param_1].maxIronmines = 4;
        this->aics[param_1].defWallPatrolGroups = 4;
        this->aics[param_1].flagType = 10;
        this->aics[param_1].unknown002 = 0;
        this->aics[param_1].unknown001 = 0;
        this->aics[param_1].unknown003 = 0;
        this->aics[param_1].unknown004 = 0;
        this->aics[param_1].unknown005 = 0;
        this->aics[param_1].criticalPopularity = 4000;
        this->aics[param_1].lowestPopularity = 5000;
        this->aics[param_1].highestPopularity = 8000;
        this->aics[param_1].farm1 = 0x1f;
        this->aics[param_1].farm4 = 0x20;
        this->aics[param_1].unknown011 = 0x14;
        this->aics[param_1].minimumApples = 5;
        this->aics[param_1].minimumCheese = 5;
        this->aics[param_1].minimumBread = 5;
        this->aics[param_1].minimumWheat = 5;
        this->aics[param_1].minimumHop = 5;
        this->aics[param_1].tradeAmountFood = 10;
        this->aics[param_1].tradeAmountEquipment = 0;
        this->aics[param_1].aiRequestDelay = 0x28;
        this->aics[param_1].minimumGoodsRequiredAfterTrade = 0x14;
        this->aics[param_1].doubleRationsFoodThreshold = 0x14;
        this->aics[param_1].maxWood = 0x3c;
        this->aics[param_1].maxResourceOther = 10;
        this->aics[param_1].maxEquipment = 5;
        this->aics[param_1].maxBeer = 10;
        this->aics[param_1].maxResourceVariance = 2;
        this->aics[param_1].recruitGoldThreshold = 200;
        this->aics[param_1].populationPerWoodcutter = 6;
        this->aics[param_1].populationPerQuarry = 10;
        this->aics[param_1].populationPerPitchrig = 0x14;
        this->aics[param_1].maxWoodcutters = 0xe;
        this->aics[param_1].maxPitchrigs = 1;
        this->aics[param_1].maxFarms = 0xf;
        this->aics[param_1].buildInterval = 2;
        this->aics[param_1].resourceRebuildDelay = 0x28;
        this->aics[param_1].blacksmithSetting = 0x16;
        this->aics[param_1].fletcherSetting = 0x12;
        this->aics[param_1].poleturnerSetting = 0x14;
        this->aics[param_1].defWallPatrolRallyTime = 3;
        this->aics[param_1].defSiegeEngineGoldThreshold = 0x14;
        this->aics[param_1].defSiegeEngineBuildDelay = 8;
        this->aics[param_1].sellResource08 = 0x11;
        this->aics[param_1].sellResource09 = 0x12;
        this->aics[param_1].sellResource11 = 0x14;
        this->aics[param_1].sellResource12 = 0x15;
        this->aics[param_1].sellResource14 = 0x17;
        this->aics[param_1].unknown072 = 100;
        this->aics[param_1].unknown073 = 0x14;
        this->aics[param_1].recruitProbDefWeak = 100;
        this->aics[param_1].recruitProbDefDefault = 0x22;
        this->aics[param_1].recruitProbDefStrong = 0x19;
        this->aics[param_1].RaidUnitsRandom = 5;
        this->aics[param_1].HarassingSiegeEnginesMax = 5;
        this->aics[param_1].RecruitIntervalWeak = 1;
        this->aics[param_1].RecruitInterval = 1;
        this->aics[param_1].RecruitIntervalStrong = 1;
        this->aics[param_1].SortieUnitRangedMin = 10;
        this->aics[param_1].OuterPatrolGroupsMove = 1;
        this->aics[param_1].OuterPatrolRallyDelay = 10;
        this->aics[param_1].RaidUnitsBase = 10;
        this->aics[param_1].AttForceRandom = 10;
        this->aics[param_1].recruitProbRaidWeak = 0;
        this->aics[param_1].recruitProbRaidStrong = 0x19;
        this->aics[param_1].recruitProbAttackWeak = 0;
        this->aics[param_1].recruitProbAttackStrong = 0x32;
        this->aics[param_1].SortieUnitMeleeMin = 7;
        this->aics[param_1].SortieUnitMelee = 0x4b;
        this->aics[param_1].DefDiggingUnitMax = 4;
        this->aics[param_1].DefDiggingUnit = 0x47;
        this->aics[param_1].DefWalls = 0x32;
        this->aics[param_1].OuterPatrolGroupsCount = 2;
        this->aics[param_1].DefUnit1 = 0x4b;
        this->aics[param_1].DefUnit5 = 0x4c;
        this->aics[param_1].RaidUnit1 = 0x4a;
        this->aics[param_1].HarassingSiegeEngine1 = 0xbe;
        this->aics[param_1].RaidRetargetDelay = 3;
        this->aics[param_1].AttForceBase = 0x32;
        this->aics[param_1].recruitProbRaidDefault = 0x21;
        this->aics[param_1].recruitProbAttackDefault = 0x21;
        this->aics[param_1].SortieUnitRanged = 0x46;
        this->aics[param_1].DefTotal = 0x46;
        this->aics[param_1].DefUnit2 = 0x46;
        this->aics[param_1].DefUnit3 = 0x46;
        this->aics[param_1].DefUnit4 = 0x46;
        this->aics[param_1].AttForceSupportAllyThreshold = 8;
        this->aics[param_1].AttForceRallyPercentage = 0x50;
        this->aics[param_1].AttMovingTribesThreshold = 100;
        this->aics[param_1].AttAssaultDelay = 4;
        this->aics[param_1].AttUnitPatrolRecommandDelay = 1;
        this->aics[param_1].AttCoordinationPreference = 0x3c;
        this->aics[param_1].CowThrowInterval = 2000;
        this->aics[param_1].SiegeEngine1 = 0x4d;
        this->aics[param_1].SiegeEngine2 = 0x4d;
        this->aics[param_1].SiegeEngine3 = 0x27;
        this->aics[param_1].SiegeEngine4 = 0x27;
        this->aics[param_1].AttMaxEngineers = 10;
        this->aics[param_1].AttDiggingUnit = 0x47;
        this->aics[param_1].AttDiggingUnitMax = 0x14;
        this->aics[param_1].AttMaxAssassins = 5;
        this->aics[param_1].AttUnit2 = 0x4a;
        this->aics[param_1].AttUnit2Max = 0x14;
        this->aics[param_1].AttMaxLaddermen = 0;
        this->aics[param_1].AttMaxTunnelers = 0;
        this->aics[param_1].AttUnitPatrol = 0x4a;
        this->aics[param_1].AttUnitPatrolMax = 0x14;
        this->aics[param_1].AttUnitPatrolGroupsCount = 1;
        this->aics[param_1].AttUnitBackup = 0x46;
        this->aics[param_1].AttUnitBackupMax = 0x14;
        this->aics[param_1].AttUnitBackupGroupsCount = 3;
        this->aics[param_1].AttUnitEngageMax = 0;
        this->aics[param_1].AttUnitEngage = 0x4c;
        this->aics[param_1].AttUnitSiegeDef = 0x4c;
        this->aics[param_1].AttUnitSiegeDefMax = 6;
        this->aics[param_1].AttUnitSiegeDefGroupsCount = 1;
        this->aics[param_1].AttUnitMain1 = 0x4b;
        this->aics[param_1].AttMaxDefault = 200;
        this->aics[param_1].AttMainGroupsCount = 3;
        this->aics[param_1].TargetChoice = AITC_GOLD;
    }
}
}
